"""parkingslotbooking table update

Revision ID: 1d2b7471d6f2
Revises: 3473d83a1c1f
Create Date: 2024-06-20 14:41:48.057953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2b7471d6f2'
down_revision: Union[str, None] = '3473d83a1c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parkingslotbooking', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parkingslotbooking', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parkingslotbooking', type_='foreignkey')
    op.drop_column('parkingslotbooking', 'user_id')
    # ### end Alembic commands ###
