"""Parkingslotbooking table add payment column added

Revision ID: 3b030b57a14a
Revises: fdc055100a61
Create Date: 2024-06-22 10:48:43.876005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b030b57a14a'
down_revision: Union[str, None] = 'fdc055100a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
