"""branch add manager column

Revision ID: 6c42aec14dcb
Revises: 0aa60354bfe8
Create Date: 2024-06-21 17:13:33.630018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c42aec14dcb'
down_revision: Union[str, None] = '0aa60354bfe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('manager', mysql.TINYINT(), nullable=True))
    op.alter_column('user', 'user_type',
               existing_type=mysql.TINYINT(),
               comment='1->SuperAdmin,2->Admin,3->Manager,4->Employee,5->customer',
               existing_comment='1->SuperAdmin,2->Admin,3->Employee,4->customer',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=mysql.TINYINT(),
               comment='1->SuperAdmin,2->Admin,3->Employee,4->customer',
               existing_comment='1->SuperAdmin,2->Admin,3->Manager,4->Employee,5->customer',
               existing_nullable=True)
    op.drop_column('branch', 'manager')
    # ### end Alembic commands ###
