"""branch table name set column unique=false

Revision ID: 720e1867013b
Revises: 64bde4b39287
Create Date: 2024-07-01 15:22:47.147540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720e1867013b'
down_revision: Union[str, None] = '64bde4b39287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='branch')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'branch', ['name'], unique=True)
    # ### end Alembic commands ###
