"""branch add manager column update

Revision ID: a3791c9b294a
Revises: 6c42aec14dcb
Create Date: 2024-06-21 17:19:00.169629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3791c9b294a'
down_revision: Union[str, None] = '6c42aec14dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'branch', 'user', ['manager_id'], ['id'])
    op.drop_column('branch', 'manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('manager', mysql.TINYINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.drop_column('branch', 'manager_id')
    # ### end Alembic commands ###
